[versions]
kotlin = "2.3.21"
logback = "1.5.21"
exposed = "0.56.0"
postgres = "42.7.4"
hikari = "6.2.1"
bcrypt = "0.10.2"
kotlinx-datetime = "0.6.1"
h2 = "2.3.232"
ktorOpenapi = "5.0.2"

[libraries]
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-java-time = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed" }

postgresql = { module = "org.postgresql:postgresql", version.ref = "postgres" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
bcrypt = { module = "at.favre.lib:bcrypt", version.ref = "bcrypt" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }

ktor-openapi = { module = "io.github.smiley4:ktor-openapi", version.ref = "ktorOpenapi" }
ktor-swagger-ui = { module = "io.github.smiley4:ktor-swagger-ui", version.ref = "ktorOpenapi" }
ktor-redoc = { module = "io.github.smiley4:ktor-redoc", version.ref = "ktorOpenapi" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
